AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway and Lambda function for account federation using IAM roles.

Parameters:
  MYSQLHost:
    Type: String
    Description: MYSQL Host Name
  MYSQLUser:
    Type: String
    Description: MYSQL User Name
  MYSQLPassword:
    Type: String
    NoEcho: true
    Description: MYSQL Password
  MYSQLDatabase:
    Type: String
    Description: MYSQL Database Name
  GoogleTokeninfoEndpoint:
    Type: String
    Default: "https://www.googleapis.com/oauth2/v3/tokeninfo?id_token="
    Description: Endpoint to Check Google Auth Token
  GithubAuthEndpoint:
    Type: String
    Default: "https://github.com/login/oauth"
    Description: Endpoint to Check Github Auth Token
  GithubAPIEndpoint:
    Type: String
    Default: "https://api.github.com"
    Description: Endpoint for Github API
  GithubClientId:
    Type: String
    Description: Client Id for Github Auth
  GithubSecret:
    Type: String
    NoEcho: true
    Description: Secret for Github Auth

Resources:
  LambdaFunctionIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: "AllowLambdaServiceToAssumeRole"
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "lambda.amazonaws.com"
          Policies:
            -
              PolicyName: "InlinePolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action:
                      - "sts:*"
                    Resource: "*"
                  -
                    Effect: "Allow"
                    Action:
                      - "logs:CreateLogGroup"
                      - "logs:CreateLogStream"
                      - "logs:PutLogEvents"
                    Resource: "arn:aws:logs:*:*:*"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./swagger.yaml
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref LambdaFunction

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python2.7
      CodeUri: ./src
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Timeout: 60
      Environment:
        Variables:
          MYSQL_HOST: !Ref MYSQLHost
          MYSQL_USER: !Ref MYSQLUser
          MYSQL_PASSWORD: !Ref MYSQLPassword
          MYSQL_DATABASE: !Ref MYSQLDatabase
          GOOGLE_TOKENINFO_ENDPOINT: !Ref GoogleTokeninfoEndpoint
          GITHUB_AUTH_ENDPOINT: !Ref GithubAuthEndpoint
          GITHUB_API_ENDPOINT: !Ref GithubAPIEndpoint
          GITHUB_CLIENT_ID: !Ref GithubClientId
          GITHUB_CLIENT_SECRET: !Ref GithubSecret
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /porper
            Method: GET

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'

  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
